# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: CameraControl.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='CameraControl.proto',
  package='CC',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x13\x43\x61meraControl.proto\x12\x02\x43\x43\"\x07\n\x05\x45mpty\"\x15\n\x06IntVal\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x18\n\tStringVal\x12\x0b\n\x03val\x18\x01 \x01(\t2\xbc\x01\n\rCameraControl\x12(\n\rIsCameraReady\x12\t.CC.Empty\x1a\n.CC.IntVal\"\x00\x12&\n\x0bIsRecording\x12\t.CC.Empty\x1a\n.CC.IntVal\"\x00\x12-\n\x0eStartRecording\x12\r.CC.StringVal\x1a\n.CC.IntVal\"\x00\x12*\n\x0f\x46inishRecording\x12\t.CC.Empty\x1a\n.CC.IntVal\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='CC.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=34,
)


_INTVAL = _descriptor.Descriptor(
  name='IntVal',
  full_name='CC.IntVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='CC.IntVal.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=57,
)


_STRINGVAL = _descriptor.Descriptor(
  name='StringVal',
  full_name='CC.StringVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='CC.StringVal.val', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=59,
  serialized_end=83,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['IntVal'] = _INTVAL
DESCRIPTOR.message_types_by_name['StringVal'] = _STRINGVAL
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'CameraControl_pb2'
  # @@protoc_insertion_point(class_scope:CC.Empty)
  })
_sym_db.RegisterMessage(Empty)

IntVal = _reflection.GeneratedProtocolMessageType('IntVal', (_message.Message,), {
  'DESCRIPTOR' : _INTVAL,
  '__module__' : 'CameraControl_pb2'
  # @@protoc_insertion_point(class_scope:CC.IntVal)
  })
_sym_db.RegisterMessage(IntVal)

StringVal = _reflection.GeneratedProtocolMessageType('StringVal', (_message.Message,), {
  'DESCRIPTOR' : _STRINGVAL,
  '__module__' : 'CameraControl_pb2'
  # @@protoc_insertion_point(class_scope:CC.StringVal)
  })
_sym_db.RegisterMessage(StringVal)



_CAMERACONTROL = _descriptor.ServiceDescriptor(
  name='CameraControl',
  full_name='CC.CameraControl',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=86,
  serialized_end=274,
  methods=[
  _descriptor.MethodDescriptor(
    name='IsCameraReady',
    full_name='CC.CameraControl.IsCameraReady',
    index=0,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='IsRecording',
    full_name='CC.CameraControl.IsRecording',
    index=1,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartRecording',
    full_name='CC.CameraControl.StartRecording',
    index=2,
    containing_service=None,
    input_type=_STRINGVAL,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='FinishRecording',
    full_name='CC.CameraControl.FinishRecording',
    index=3,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_CAMERACONTROL)

DESCRIPTOR.services_by_name['CameraControl'] = _CAMERACONTROL

# @@protoc_insertion_point(module_scope)
