# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import EtherCATCommgRPCServer_pb2 as EtherCATCommgRPCServer__pb2


class GRPCECatTaskStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMasterStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMasterStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetSlaveStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetSlaveStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                )
        self.GetRxDomainStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetRxDomainStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetTxDomainStatus = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetTxDomainStatus',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.IsSystemReady = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/IsSystemReady',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVals.FromString,
                )
        self.SetServoOnOff = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetServoOnOff',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoIndex.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetRxPDOMotorDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetRxPDOMotorDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.MotorDriverRxIndex.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetRxPDOMotorDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetRxPDOMotorDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.MotorDriverRx.FromString,
                )
        self.GetTxPDOMotorDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetTxPDOMotorDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.MotorDriverTx.FromString,
                )
        self.GetMotorDriverDIs = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMotorDriverDIs',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetErrorCode = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetErrorCode',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetMaxTorque = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMaxTorque',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.SetMaxTorque = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetMaxTorque',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetMaxMotorSpeed = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMaxMotorSpeed',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.SetMaxMotorSpeed = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetMaxMotorSpeed',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetNRMKIOBoardOutput = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetNRMKIOBoardOutput',
                request_serializer=EtherCATCommgRPCServer__pb2.IOBoardRx.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetNRMKIOBoardInput = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetNRMKIOBoardInput',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IOBoardTx.FromString,
                )
        self.GetNRMKIOBoardOutput = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetNRMKIOBoardOutput',
                request_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IOBoardRx.FromString,
                )
        self.SetDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetDO',
                request_serializer=EtherCATCommgRPCServer__pb2.DOList.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetDI = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetDI',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.DIList.FromString,
                )
        self.GetDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.DOList.FromString,
                )
        self.GetRobotusFTSensor = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetRobotusFTSensor',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.RobotusFTTx.FromString,
                )
        self.ResetWelconDriver = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/ResetWelconDriver',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.GetCOREErrorCodeSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCOREErrorCodeSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetCORETemperature1SDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCORETemperature1SDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.FloatVal.FromString,
                )
        self.GetCORETemperature2SDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCORETemperature2SDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.FloatVal.FromString,
                )
        self.GetCORETemperature3SDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetCORETemperature3SDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.FloatVal.FromString,
                )
        self.GetNRMKFWVersionSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetNRMKFWVersionSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.StringVal.FromString,
                )
        self.GetMaxTorqueSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetMaxTorqueSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetProfileVelocitySDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetProfileVelocitySDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetProfileAccSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetProfileAccSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.GetProfileDecSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/GetProfileDecSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                )
        self.SetMaxTorqueSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetMaxTorqueSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetProfileVelocitySDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetProfileVelocitySDO',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetProfileAccSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetProfileAccSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )
        self.SetProfileDecSDO = channel.unary_unary(
                '/GRPCECat.GRPCECatTask/SetProfileDecSDO',
                request_serializer=EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
                response_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                )


class GRPCECatTaskServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMasterStatus(self, request, context):
        """Master and slave status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSlaveStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRxDomainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxDomainStatus(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsSystemReady(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetServoOnOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRxPDOMotorDriver(self, request, context):
        """Read and Write PDOs (Motor Driver)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRxPDOMotorDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTxPDOMotorDriver(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMotorDriverDIs(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetErrorCode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaxTorque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaxTorque(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaxMotorSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaxMotorSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetNRMKIOBoardOutput(self, request, context):
        """Read and Write PDOs (Neuromeka IO board)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNRMKIOBoardInput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNRMKIOBoardOutput(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDO(self, request, context):
        """Read and Write PDOs (Beckhoff)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDI(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRobotusFTSensor(self, request, context):
        """Read and Write PDOs (Robotus FT sensor)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetWelconDriver(self, request, context):
        """Motor drive control
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCOREErrorCodeSDO(self, request, context):
        """Read and Write SDOs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCORETemperature1SDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCORETemperature2SDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCORETemperature3SDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetNRMKFWVersionSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMaxTorqueSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileVelocitySDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileAccSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProfileDecSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetMaxTorqueSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileVelocitySDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileAccSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetProfileDecSDO(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCECatTaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMasterStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMasterStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetSlaveStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSlaveStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            ),
            'GetRxDomainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRxDomainStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetTxDomainStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxDomainStatus,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'IsSystemReady': grpc.unary_unary_rpc_method_handler(
                    servicer.IsSystemReady,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVals.SerializeToString,
            ),
            'SetServoOnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.SetServoOnOff,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoIndex.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetRxPDOMotorDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRxPDOMotorDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.MotorDriverRxIndex.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetRxPDOMotorDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRxPDOMotorDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.MotorDriverRx.SerializeToString,
            ),
            'GetTxPDOMotorDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTxPDOMotorDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.MotorDriverTx.SerializeToString,
            ),
            'GetMotorDriverDIs': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMotorDriverDIs,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetErrorCode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetErrorCode,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetMaxTorque': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaxTorque,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'SetMaxTorque': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaxTorque,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoParam.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetMaxMotorSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaxMotorSpeed,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'SetMaxMotorSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaxMotorSpeed,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoParam.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetNRMKIOBoardOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.SetNRMKIOBoardOutput,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IOBoardRx.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetNRMKIOBoardInput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNRMKIOBoardInput,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IOBoardTx.SerializeToString,
            ),
            'GetNRMKIOBoardOutput': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNRMKIOBoardOutput,
                    request_deserializer=EtherCATCommgRPCServer__pb2.Empty.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IOBoardRx.SerializeToString,
            ),
            'SetDO': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.DOList.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetDI': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDI,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.DIList.SerializeToString,
            ),
            'GetDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.DOList.SerializeToString,
            ),
            'GetRobotusFTSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRobotusFTSensor,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.RobotusFTTx.SerializeToString,
            ),
            'ResetWelconDriver': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetWelconDriver,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetCOREErrorCodeSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCOREErrorCodeSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetCORETemperature1SDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCORETemperature1SDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.FloatVal.SerializeToString,
            ),
            'GetCORETemperature2SDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCORETemperature2SDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.FloatVal.SerializeToString,
            ),
            'GetCORETemperature3SDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCORETemperature3SDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.FloatVal.SerializeToString,
            ),
            'GetNRMKFWVersionSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNRMKFWVersionSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.StringVal.SerializeToString,
            ),
            'GetMaxTorqueSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMaxTorqueSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetProfileVelocitySDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileVelocitySDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetProfileAccSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileAccSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetProfileDecSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProfileDecSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.IntVal.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            ),
            'SetMaxTorqueSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.SetMaxTorqueSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoParam.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetProfileVelocitySDO': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileVelocitySDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoParam.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetProfileAccSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileAccSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoParam.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetProfileDecSDO': grpc.unary_unary_rpc_method_handler(
                    servicer.SetProfileDecSDO,
                    request_deserializer=EtherCATCommgRPCServer__pb2.ServoParam.FromString,
                    response_serializer=EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCECat.GRPCECatTask', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCECatTask(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMasterStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMasterStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetSlaveStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetSlaveStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVals.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRxDomainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetRxDomainStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTxDomainStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetTxDomainStatus',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def IsSystemReady(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/IsSystemReady',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVals.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetServoOnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetServoOnOff',
            EtherCATCommgRPCServer__pb2.ServoIndex.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRxPDOMotorDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetRxPDOMotorDriver',
            EtherCATCommgRPCServer__pb2.MotorDriverRxIndex.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRxPDOMotorDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetRxPDOMotorDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.MotorDriverRx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTxPDOMotorDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetTxPDOMotorDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.MotorDriverTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMotorDriverDIs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMotorDriverDIs',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetErrorCode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetErrorCode',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaxTorque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMaxTorque',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMaxTorque(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetMaxTorque',
            EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaxMotorSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMaxMotorSpeed',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMaxMotorSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetMaxMotorSpeed',
            EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetNRMKIOBoardOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetNRMKIOBoardOutput',
            EtherCATCommgRPCServer__pb2.IOBoardRx.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNRMKIOBoardInput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetNRMKIOBoardInput',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IOBoardTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNRMKIOBoardOutput(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetNRMKIOBoardOutput',
            EtherCATCommgRPCServer__pb2.Empty.SerializeToString,
            EtherCATCommgRPCServer__pb2.IOBoardRx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetDO',
            EtherCATCommgRPCServer__pb2.DOList.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDI(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetDI',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.DIList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.DOList.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRobotusFTSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetRobotusFTSensor',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.RobotusFTTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetWelconDriver(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/ResetWelconDriver',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCOREErrorCodeSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCOREErrorCodeSDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCORETemperature1SDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCORETemperature1SDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.FloatVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCORETemperature2SDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCORETemperature2SDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.FloatVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCORETemperature3SDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetCORETemperature3SDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.FloatVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetNRMKFWVersionSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetNRMKFWVersionSDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.StringVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMaxTorqueSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetMaxTorqueSDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileVelocitySDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetProfileVelocitySDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileAccSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetProfileAccSDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetProfileDecSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/GetProfileDecSDO',
            EtherCATCommgRPCServer__pb2.IntVal.SerializeToString,
            EtherCATCommgRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetMaxTorqueSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetMaxTorqueSDO',
            EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileVelocitySDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetProfileVelocitySDO',
            EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileAccSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetProfileAccSDO',
            EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetProfileDecSDO(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCECat.GRPCECatTask/SetProfileDecSDO',
            EtherCATCommgRPCServer__pb2.ServoParam.SerializeToString,
            EtherCATCommgRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
