# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GlobalVariablegRPCServer.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='GlobalVariablegRPCServer.proto',
  package='GRPCGlobalVariable',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1eGlobalVariablegRPCServer.proto\x12\x12GRPCGlobalVariable\"\x07\n\x05\x45mpty\" \n\x04GInt\x12\x0b\n\x03idx\x18\x01 \x01(\x05\x12\x0b\n\x03val\x18\x02 \x01(\x05\"\x15\n\x06IntVal\x12\x0b\n\x03val\x18\x01 \x01(\x05\"\x16\n\x07IntVals\x12\x0b\n\x03val\x18\x01 \x03(\x05\x32\xc7\x03\n\x16GRPCGlobalVariableTask\x12?\n\x06SetInt\x12\x18.GRPCGlobalVariable.GInt\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x42\n\x06GetInt\x12\x1a.GRPCGlobalVariable.IntVal\x1a\x1a.GRPCGlobalVariable.IntVal\"\x00\x12\x43\n\x07SetInts\x12\x1b.GRPCGlobalVariable.IntVals\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12\x45\n\x07GetInts\x12\x1b.GRPCGlobalVariable.IntVals\x1a\x1b.GRPCGlobalVariable.IntVals\"\x00\x12M\n\x13SaveGlobalVariables\x12\x19.GRPCGlobalVariable.Empty\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x12M\n\x13LoadGlobalVariables\x12\x19.GRPCGlobalVariable.Empty\x1a\x19.GRPCGlobalVariable.Empty\"\x00\x62\x06proto3'
)




_EMPTY = _descriptor.Descriptor(
  name='Empty',
  full_name='GRPCGlobalVariable.Empty',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=61,
)


_GINT = _descriptor.Descriptor(
  name='GInt',
  full_name='GRPCGlobalVariable.GInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='idx', full_name='GRPCGlobalVariable.GInt.idx', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.GInt.val', index=1,
      number=2, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=63,
  serialized_end=95,
)


_INTVAL = _descriptor.Descriptor(
  name='IntVal',
  full_name='GRPCGlobalVariable.IntVal',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.IntVal.val', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=97,
  serialized_end=118,
)


_INTVALS = _descriptor.Descriptor(
  name='IntVals',
  full_name='GRPCGlobalVariable.IntVals',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='val', full_name='GRPCGlobalVariable.IntVals.val', index=0,
      number=1, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=120,
  serialized_end=142,
)

DESCRIPTOR.message_types_by_name['Empty'] = _EMPTY
DESCRIPTOR.message_types_by_name['GInt'] = _GINT
DESCRIPTOR.message_types_by_name['IntVal'] = _INTVAL
DESCRIPTOR.message_types_by_name['IntVals'] = _INTVALS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Empty = _reflection.GeneratedProtocolMessageType('Empty', (_message.Message,), {
  'DESCRIPTOR' : _EMPTY,
  '__module__' : 'GlobalVariablegRPCServer_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.Empty)
  })
_sym_db.RegisterMessage(Empty)

GInt = _reflection.GeneratedProtocolMessageType('GInt', (_message.Message,), {
  'DESCRIPTOR' : _GINT,
  '__module__' : 'GlobalVariablegRPCServer_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.GInt)
  })
_sym_db.RegisterMessage(GInt)

IntVal = _reflection.GeneratedProtocolMessageType('IntVal', (_message.Message,), {
  'DESCRIPTOR' : _INTVAL,
  '__module__' : 'GlobalVariablegRPCServer_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.IntVal)
  })
_sym_db.RegisterMessage(IntVal)

IntVals = _reflection.GeneratedProtocolMessageType('IntVals', (_message.Message,), {
  'DESCRIPTOR' : _INTVALS,
  '__module__' : 'GlobalVariablegRPCServer_pb2'
  # @@protoc_insertion_point(class_scope:GRPCGlobalVariable.IntVals)
  })
_sym_db.RegisterMessage(IntVals)



_GRPCGLOBALVARIABLETASK = _descriptor.ServiceDescriptor(
  name='GRPCGlobalVariableTask',
  full_name='GRPCGlobalVariable.GRPCGlobalVariableTask',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=145,
  serialized_end=600,
  methods=[
  _descriptor.MethodDescriptor(
    name='SetInt',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.SetInt',
    index=0,
    containing_service=None,
    input_type=_GINT,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInt',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.GetInt',
    index=1,
    containing_service=None,
    input_type=_INTVAL,
    output_type=_INTVAL,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SetInts',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.SetInts',
    index=2,
    containing_service=None,
    input_type=_INTVALS,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetInts',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.GetInts',
    index=3,
    containing_service=None,
    input_type=_INTVALS,
    output_type=_INTVALS,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='SaveGlobalVariables',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.SaveGlobalVariables',
    index=4,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LoadGlobalVariables',
    full_name='GRPCGlobalVariable.GRPCGlobalVariableTask.LoadGlobalVariables',
    index=5,
    containing_service=None,
    input_type=_EMPTY,
    output_type=_EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_GRPCGLOBALVARIABLETASK)

DESCRIPTOR.services_by_name['GRPCGlobalVariableTask'] = _GRPCGLOBALVARIABLETASK

# @@protoc_insertion_point(module_scope)
