# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import MobygRPCServer_pb2 as MobygRPCServer__pb2


class GRPCMobyTaskStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMobyTxData = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetMobyTxData',
                request_serializer=MobygRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.MotorDriverTx.FromString,
                )
        self.GetMobyRxData = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetMobyRxData',
                request_serializer=MobygRPCServer__pb2.IntVal.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.MotorDriverRx.FromString,
                )
        self.DirectMotorDriveControl = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/DirectMotorDriveControl',
                request_serializer=MobygRPCServer__pb2.MotorDriverRxs.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.GetMobyState = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetMobyState',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.MobyState.FromString,
                )
        self.GetMobyErrorState = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetMobyErrorState',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.MobyErrorState.FromString,
                )
        self.Recover = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/Recover',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.GetMobyPose = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetMobyPose',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.MobyPose.FromString,
                )
        self.GetMobyVel = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetMobyVel',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.MobyVel.FromString,
                )
        self.ResetMobyPose = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/ResetMobyPose',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.GetRotationAngleDeg = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetRotationAngleDeg',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.SwerveDoubles.FromString,
                )
        self.GetDriveSpeed = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetDriveSpeed',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.SwerveDoubles.FromString,
                )
        self.GetTargetVel = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetTargetVel',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.TargetVel.FromString,
                )
        self.GetRotationZeroCount = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetRotationZeroCount',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.ZeroCount.FromString,
                )
        self.GetCMode = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetCMode',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.IntVal.FromString,
                )
        self.GetGyroData = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetGyroData',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.DoubleVals.FromString,
                )
        self.ResetGyroSensor = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/ResetGyroSensor',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.UseGyroForOdom = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/UseGyroForOdom',
                request_serializer=MobygRPCServer__pb2.BoolVal.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.GetGyroFullData = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetGyroFullData',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.IMUData.FromString,
                )
        self.GetIRSensorData = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetIRSensorData',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.IRData.FromString,
                )
        self.GetBMSData = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/GetBMSData',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.BMSData.FromString,
                )
        self.SetStepControl = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetStepControl',
                request_serializer=MobygRPCServer__pb2.TargetVel.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.StopMotion = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/StopMotion',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetRotationAngleDeg = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetRotationAngleDeg',
                request_serializer=MobygRPCServer__pb2.SwerveDoubles.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetZeroPosAsCurrentPos = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetZeroPosAsCurrentPos',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetRotationVelAcc = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetRotationVelAcc',
                request_serializer=MobygRPCServer__pb2.DoubleVals.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetDriveAccDec = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetDriveAccDec',
                request_serializer=MobygRPCServer__pb2.DoubleVals.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetDriveInterpolatorOnOff = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetDriveInterpolatorOnOff',
                request_serializer=MobygRPCServer__pb2.BoolVal.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetRotationInterpolatorParam = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetRotationInterpolatorParam',
                request_serializer=MobygRPCServer__pb2.DoubleVals.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetRotationTorqueMode = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetRotationTorqueMode',
                request_serializer=MobygRPCServer__pb2.BoolVal.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetControlParam = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetControlParam',
                request_serializer=MobygRPCServer__pb2.RotationGain.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.StartRTLogging = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/StartRTLogging',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.EndRTLogging = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/EndRTLogging',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.SetLoggerBuffer = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/SetLoggerBuffer',
                request_serializer=MobygRPCServer__pb2.IntVals.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )
        self.RTLoggerSave = channel.unary_unary(
                '/GRPCMoby.GRPCMobyTask/RTLoggerSave',
                request_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
                response_deserializer=MobygRPCServer__pb2.Empty.FromString,
                )


class GRPCMobyTaskServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMobyTxData(self, request, context):
        """Moby EtherCAT TxPDO and RxPDO data processing
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobyRxData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DirectMotorDriveControl(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobyState(self, request, context):
        """Get Moby state
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobyErrorState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Recover(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobyPose(self, request, context):
        """Get Moby battery and charging state

        Get Moby's odometry and physical data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetMobyVel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetMobyPose(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRotationAngleDeg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetDriveSpeed(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTargetVel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetRotationZeroCount(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCMode(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGyroData(self, request, context):
        """Gyro value related
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ResetGyroSensor(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UseGyroForOdom(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetGyroFullData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetIRSensorData(self, request, context):
        """IR sensor
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetBMSData(self, request, context):
        """BMS data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetStepControl(self, request, context):
        """Moby motion command
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopMotion(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRotationAngleDeg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetZeroPosAsCurrentPos(self, request, context):
        """Set Moby parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRotationVelAcc(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDriveAccDec(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetDriveInterpolatorOnOff(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRotationInterpolatorParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetRotationTorqueMode(self, request, context):
        """Gain setting
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetControlParam(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartRTLogging(self, request, context):
        """Data logging
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndRTLogging(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetLoggerBuffer(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RTLoggerSave(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_GRPCMobyTaskServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMobyTxData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobyTxData,
                    request_deserializer=MobygRPCServer__pb2.IntVal.FromString,
                    response_serializer=MobygRPCServer__pb2.MotorDriverTx.SerializeToString,
            ),
            'GetMobyRxData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobyRxData,
                    request_deserializer=MobygRPCServer__pb2.IntVal.FromString,
                    response_serializer=MobygRPCServer__pb2.MotorDriverRx.SerializeToString,
            ),
            'DirectMotorDriveControl': grpc.unary_unary_rpc_method_handler(
                    servicer.DirectMotorDriveControl,
                    request_deserializer=MobygRPCServer__pb2.MotorDriverRxs.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetMobyState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobyState,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.MobyState.SerializeToString,
            ),
            'GetMobyErrorState': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobyErrorState,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.MobyErrorState.SerializeToString,
            ),
            'Recover': grpc.unary_unary_rpc_method_handler(
                    servicer.Recover,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetMobyPose': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobyPose,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.MobyPose.SerializeToString,
            ),
            'GetMobyVel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMobyVel,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.MobyVel.SerializeToString,
            ),
            'ResetMobyPose': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetMobyPose,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetRotationAngleDeg': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRotationAngleDeg,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.SwerveDoubles.SerializeToString,
            ),
            'GetDriveSpeed': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDriveSpeed,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.SwerveDoubles.SerializeToString,
            ),
            'GetTargetVel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTargetVel,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.TargetVel.SerializeToString,
            ),
            'GetRotationZeroCount': grpc.unary_unary_rpc_method_handler(
                    servicer.GetRotationZeroCount,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.ZeroCount.SerializeToString,
            ),
            'GetCMode': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCMode,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.IntVal.SerializeToString,
            ),
            'GetGyroData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGyroData,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.DoubleVals.SerializeToString,
            ),
            'ResetGyroSensor': grpc.unary_unary_rpc_method_handler(
                    servicer.ResetGyroSensor,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'UseGyroForOdom': grpc.unary_unary_rpc_method_handler(
                    servicer.UseGyroForOdom,
                    request_deserializer=MobygRPCServer__pb2.BoolVal.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'GetGyroFullData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetGyroFullData,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.IMUData.SerializeToString,
            ),
            'GetIRSensorData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetIRSensorData,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.IRData.SerializeToString,
            ),
            'GetBMSData': grpc.unary_unary_rpc_method_handler(
                    servicer.GetBMSData,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.BMSData.SerializeToString,
            ),
            'SetStepControl': grpc.unary_unary_rpc_method_handler(
                    servicer.SetStepControl,
                    request_deserializer=MobygRPCServer__pb2.TargetVel.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'StopMotion': grpc.unary_unary_rpc_method_handler(
                    servicer.StopMotion,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetRotationAngleDeg': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRotationAngleDeg,
                    request_deserializer=MobygRPCServer__pb2.SwerveDoubles.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetZeroPosAsCurrentPos': grpc.unary_unary_rpc_method_handler(
                    servicer.SetZeroPosAsCurrentPos,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetRotationVelAcc': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRotationVelAcc,
                    request_deserializer=MobygRPCServer__pb2.DoubleVals.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetDriveAccDec': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDriveAccDec,
                    request_deserializer=MobygRPCServer__pb2.DoubleVals.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetDriveInterpolatorOnOff': grpc.unary_unary_rpc_method_handler(
                    servicer.SetDriveInterpolatorOnOff,
                    request_deserializer=MobygRPCServer__pb2.BoolVal.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetRotationInterpolatorParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRotationInterpolatorParam,
                    request_deserializer=MobygRPCServer__pb2.DoubleVals.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetRotationTorqueMode': grpc.unary_unary_rpc_method_handler(
                    servicer.SetRotationTorqueMode,
                    request_deserializer=MobygRPCServer__pb2.BoolVal.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetControlParam': grpc.unary_unary_rpc_method_handler(
                    servicer.SetControlParam,
                    request_deserializer=MobygRPCServer__pb2.RotationGain.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'StartRTLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.StartRTLogging,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'EndRTLogging': grpc.unary_unary_rpc_method_handler(
                    servicer.EndRTLogging,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'SetLoggerBuffer': grpc.unary_unary_rpc_method_handler(
                    servicer.SetLoggerBuffer,
                    request_deserializer=MobygRPCServer__pb2.IntVals.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
            'RTLoggerSave': grpc.unary_unary_rpc_method_handler(
                    servicer.RTLoggerSave,
                    request_deserializer=MobygRPCServer__pb2.Empty.FromString,
                    response_serializer=MobygRPCServer__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'GRPCMoby.GRPCMobyTask', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class GRPCMobyTask(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMobyTxData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetMobyTxData',
            MobygRPCServer__pb2.IntVal.SerializeToString,
            MobygRPCServer__pb2.MotorDriverTx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobyRxData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetMobyRxData',
            MobygRPCServer__pb2.IntVal.SerializeToString,
            MobygRPCServer__pb2.MotorDriverRx.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def DirectMotorDriveControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/DirectMotorDriveControl',
            MobygRPCServer__pb2.MotorDriverRxs.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobyState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetMobyState',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.MobyState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobyErrorState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetMobyErrorState',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.MobyErrorState.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Recover(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/Recover',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobyPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetMobyPose',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.MobyPose.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetMobyVel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetMobyVel',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.MobyVel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetMobyPose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/ResetMobyPose',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRotationAngleDeg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetRotationAngleDeg',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.SwerveDoubles.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetDriveSpeed(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetDriveSpeed',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.SwerveDoubles.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetTargetVel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetTargetVel',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.TargetVel.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetRotationZeroCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetRotationZeroCount',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.ZeroCount.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetCMode',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.IntVal.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGyroData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetGyroData',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.DoubleVals.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def ResetGyroSensor(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/ResetGyroSensor',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def UseGyroForOdom(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/UseGyroForOdom',
            MobygRPCServer__pb2.BoolVal.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetGyroFullData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetGyroFullData',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.IMUData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetIRSensorData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetIRSensorData',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.IRData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetBMSData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/GetBMSData',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.BMSData.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetStepControl(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetStepControl',
            MobygRPCServer__pb2.TargetVel.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StopMotion(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/StopMotion',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRotationAngleDeg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetRotationAngleDeg',
            MobygRPCServer__pb2.SwerveDoubles.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetZeroPosAsCurrentPos(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetZeroPosAsCurrentPos',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRotationVelAcc(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetRotationVelAcc',
            MobygRPCServer__pb2.DoubleVals.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDriveAccDec(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetDriveAccDec',
            MobygRPCServer__pb2.DoubleVals.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetDriveInterpolatorOnOff(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetDriveInterpolatorOnOff',
            MobygRPCServer__pb2.BoolVal.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRotationInterpolatorParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetRotationInterpolatorParam',
            MobygRPCServer__pb2.DoubleVals.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetRotationTorqueMode(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetRotationTorqueMode',
            MobygRPCServer__pb2.BoolVal.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetControlParam(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetControlParam',
            MobygRPCServer__pb2.RotationGain.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartRTLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/StartRTLogging',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndRTLogging(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/EndRTLogging',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SetLoggerBuffer(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/SetLoggerBuffer',
            MobygRPCServer__pb2.IntVals.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def RTLoggerSave(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/GRPCMoby.GRPCMobyTask/RTLoggerSave',
            MobygRPCServer__pb2.Empty.SerializeToString,
            MobygRPCServer__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
