# How links connect together
kinematics:
  base_joint:
    x: 0
    y: 0
    z: 0.066
    roll: 0
    pitch: 0
    yaw: 0
  imu_joint:
    x: 0.183
    y: 0
    z: 0.210
    roll: 0
    pitch: 0
    yaw: 0
    
  front_camera_joint:
    x: 0.475
    y: 0
    z: 0.25
    roll: 0
    pitch: 0
    yaw: 0
  rear_camera_joint:
    x: -0.475
    y: 0
    z: 0.25
    roll: 0
    pitch: 0
    yaw: 3.1415926536
  right_camera_joint:
    x: 0
    y: -0.3
    z: 0.25
    roll: 0
    pitch: 0
    yaw: -1.570796327
  left_camera_joint:
    x: 0
    y: 0.3
    z: 0.25
    roll: 0
    pitch: 0
    yaw: 1.570796327

  front_lidar_joint:
    x: 0.421
    y: -0.246
    z: 0.210
    roll: 3.1415926536
    pitch: 0
    yaw: -0.7853981634
  rear_lidar_joint:
    x: -0.421
    y: 0.246
    z: 0.210
    roll: 3.1415926536
    pitch: 0
    yaw: 2.35619449019

  fl_rot_joint:
    x: 0.365
    y: 0.206
    z: 0.035
    roll: 0
    pitch: 0
    yaw: 0
  fl_tract_joint:
    x: 0
    y: 0
    z: 0
    roll: -1.570796327
    pitch: 0
    yaw: 0

  fr_rot_joint:
    x: 0.365
    y: -0.206
    z: 0.035
    roll: 0
    pitch: 0
    yaw: 0
  fr_tract_joint:
    x: 0
    y: 0
    z: 0
    roll: -1.570796327
    pitch: 0
    yaw: 0

  rl_rot_joint:
    x: -0.365
    y: 0.206
    z: 0.035
    roll: 0
    pitch: 0
    yaw: 0
  rl_tract_joint:
    x: 0
    y: 0
    z: 0
    roll: -1.570796327
    pitch: 0
    yaw: 0

  rr_rot_joint:
    x: -0.365
    y: -0.206
    z: 0.035
    roll: 0
    pitch: 0
    yaw: 0
  rr_tract_joint:
    x: 0
    y: 0
    z: 0
    roll: -1.570796327
    pitch: 0
    yaw: 0
  
  base_arm:
    x: 0.3375
    y: 0
    z: 0.440
    roll: 0
    pitch: 0
    yaw: 0

  joint0:
    x: 0
    y: 0
    z: 0.0775
    roll: 0
    pitch: 0
    yaw: 0
  joint1:
    x: 0
    y: -0.109
    z: 0.222
    roll: 1.570796327
    pitch: 1.570796327
    yaw: 0
  joint2:
    x: -0.45
    y: 0
    z: -0.0305
    roll: 0
    pitch: 0
    yaw: 0
  joint3:
    x: -0.267
    y: 0
    z: -0.075
    roll: -1.570796327
    pitch: 0
    yaw: 1.570796327
  joint4:
    x: 0
    y: -0.114
    z: +0.083
    roll: 1.570796327
    pitch: 1.570796327
    yaw: 0
  joint5:
    x: -0.168
    y: 0
    z: 0.069
    roll: -1.570796327
    pitch: 0
    yaw: 1.570796327
  ir_front1_joint:
    x: 0.475
    y: -0.1
    z: 0.05
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  ir_front2_joint:
    x: 0.475
    y: 0.1
    z: 0.05
    roll: 0.0
    pitch: 0.0
    yaw: 0.0
  ir_left1_joint:
    x: 0.2
    y: 0.3
    z: 0.05
    roll: 0
    pitch: 0
    yaw: 1.570796327
  ir_left2_joint:
    x: 0.0
    y: 0.3
    z: 0.05
    roll: 0
    pitch: 0
    yaw: 1.570796327
  ir_left3_joint:
    x: -0.2
    y: 0.3
    z: 0.05
    roll: 0
    pitch: 0
    yaw: 1.570796327
  ir_rear_joint:
    x: -0.475
    y: 0.0
    z: 0.05
    roll: 0
    pitch: 0
    yaw: 3.1415926536
  ir_right1_joint:
    x: -0.2
    y: -0.3
    z: 0.05
    roll: 0
    pitch: 0
    yaw: -1.570796327
  ir_right2_joint:
    x: 0.0
    y: -0.3
    z: 0.05
    roll: 0
    pitch: 0
    yaw: -1.570796327
  ir_right3_joint:
    x: 0.2
    y: -0.3
    z: 0.05
    roll: 0
    pitch: 0
    yaw: -1.570796327
