mesh_files:
  moby_frame:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/moby_rp.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/moby_rp.stl
  moby_wheel:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/wheel_rp.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/wheel_rp.stl
  link0:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_0.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_0.stl
  link1:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_1.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_1.stl
  link2:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_2.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_2.stl
  link3:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_3.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_3.stl
  link4:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_4.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_4.stl
  link5:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_5.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_5.stl
  link6:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_6.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_6.stl
  link6_indyeye:
    visual:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_eye_6.stl
    collision:
      mesh:
        package: moby_description
        path: meshes/moby_rp/stl/Indy7_eye_6.stl
