amcl:
  ros__parameters:
    use_sim_time: False
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 20.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 100
    max_particles: 4000
    min_particles: 1000
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::OmniMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 0.2 #1.0
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: /scan
    map_topic: /map
    first_map_only: true
    set_initial_pose: true
    initial_pose:
      x: 0.0
      y: 0.0
      z: 0.0
      yaw: 0.0

amcl_map_client:
  ros__parameters:
    use_sim_time: False

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: False

bt_navigator:
  ros__parameters:
    use_sim_time: False
    global_frame: map
    robot_base_frame: base_link
    odom_topic: /odom
    default_nav_to_pose_bt_xml: /home/user/ros2_ws/install/moby_navigation/share/moby_navigation/behavior_trees/navigate_to_pose_w_replanning_and_recovery.xml
    default_nav_through_poses_bt_xml: /home/user/ros2_ws/install/moby_navigation/share/moby_navigation/behavior_trees/navigate_through_poses_w_replanning_and_recovery.xml
    plugin_lib_names:
    - nav2_compute_path_to_pose_action_bt_node
    - nav2_follow_path_action_bt_node
    - nav2_back_up_action_bt_node
    - nav2_spin_action_bt_node
    - nav2_wait_action_bt_node
    - nav2_clear_costmap_service_bt_node
    - nav2_is_stuck_condition_bt_node
    - nav2_goal_reached_condition_bt_node
    - nav2_goal_updated_condition_bt_node
    - nav2_initial_pose_received_condition_bt_node
    - nav2_reinitialize_global_localization_service_bt_node
    - nav2_rate_controller_bt_node
    - nav2_distance_controller_bt_node
    - nav2_speed_controller_bt_node
    - nav2_recovery_node_bt_node
    - nav2_pipeline_sequence_bt_node
    - nav2_round_robin_node_bt_node
    - nav2_transform_available_condition_bt_node
    - nav2_time_expired_condition_bt_node
    - nav2_distance_traveled_condition_bt_node

bt_navigator_rclcpp_node:
  ros__parameters:
    use_sim_time: False

controller_server:
  ros__parameters:
    use_sim_time: False
    controller_frequency: 50.0
#    speed_limit_topic: speed_limit
    min_x_velocity_threshold: 0.001
    min_y_velocity_threshold: 0.001
    min_theta_velocity_threshold: 0.001
    progress_checker_plugin: "progress_checker"
    goal_checker_plugin: "goal_checker"
    controller_plugins: ["FollowPath"]
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.3
      movement_time_allowance: 30.0
    goal_checker:
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.05 # 0.05 # meter
      yaw_goal_tolerance: 0.1 # 0.1 # 5.73 deg
      stateful: True
    # TEB parameters
    FollowPath:
      plugin: "teb_local_planner::TebLocalPlannerROS"
      dt_ref: 0.3
      dt_hysteresis: 0.1
      min_turning_radius: 0.0
      footprint_model: # types: "point", "circular", "two_circles", "line", "polygon"
        type: "line"
        line_start: [ 0.365, 0.0 ]
        line_end: [ -0.365, 0.0 ]
      min_obstacle_dist: 0.33
      inflation_dist: 0.4
      costmap_converter_plugin: "costmap_converter::CostmapToPolygonsDBSMCCH"
      costmap_converter_spin_thread: True
      costmap_converter_rate: 15
      include_costmap_obstacles: True
      enable_homotopy_class_planning: True
      enable_multithreading: True
      optimization_verbose: False
      teb_autoresize: True
      min_samples: 3
      max_samples: 20
      max_global_plan_lookahead_dist: 4.0
      visualize_hc_graph: True
      max_vel_x: 0.25
      max_vel_y: 0.0
      max_vel_theta: 0.25
      max_vel_x_backwards: 0.25
      acc_lim_x: 0.051
      acc_lim_y: 0.0
      acc_lim_theta: 0.051
      penalty_epsilon: 0.05
      holonomic_robot: True
      weight_kinematics_nh: 10000.0
      weight_kinematics_forward_drive: 0.0
      weight_optimaltime: 1.0

controller_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

local_costmap:
  local_costmap:
    ros__parameters:
      update_frequency: 5.0
      publish_frequency: 2.0
      global_frame: odom
      robot_base_frame: base_link
      use_sim_time: False
      rolling_window: true
      width: 6
      height: 6
#      robot_radius: 0.2
      footprint: "[ [0.475, 0.3], [0.475, -0.3], [-0.475, -0.3], [-0.475, 0.3] ]"
      resolution: 0.05
#      plugins: ["obstacle_layer", "voxel_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 13.7
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: front_scan rear_scan
        front_scan:
          topic: /front_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 4.0
          raytrace_max_range: 5.0
          data_type: "LaserScan"
        rear_scan:
          topic: /rear_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 4.0
          raytrace_max_range: 5.0
          data_type: "LaserScan"
#      voxel_layer:
#        plugin: "nav2_costmap_2d::VoxelLayer"
#        enabled: True
#        publish_voxel_map: True
#        origin_z: 0.0
#        z_resolution: 0.05
#        z_voxels: 16
#        max_obstacle_height: 2.0
#        mark_threshold: 0
#        observation_sources: pointcloud
#        pointcloud:
#          topic: /merged_cloud
#          max_obstacle_height: 2.0
#          clearing: True
#          marking: True
#          data_type: "PointCloud2"
      static_layer:
        map_subscribe_transient_local: True
      always_send_full_costmap: True
  local_costmap_client:
    ros__parameters:
      use_sim_time: False
  local_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

global_costmap:
  global_costmap:
    ros__parameters:
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: base_link
      use_sim_time: False
      footprint: "[ [0.475, 0.3], [0.475, -0.3], [-0.475, -0.3], [-0.475, 0.3] ]"
      resolution: 0.05
#      plugins: ["static_layer", "obstacle_layer", "voxel_layer", "inflation_layer"]
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: front_scan rear_scan
        front_scan:
          topic: /front_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 7.0
          raytrace_max_range: 8.0
          data_type: "LaserScan"
        rear_scan:
          topic: /rear_lidar/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          obstacle_max_range: 7.0
          raytrace_max_range: 8.0
          data_type: "LaserScan"
#      voxel_layer:
#        plugin: "nav2_costmap_2d::VoxelLayer"
#        enabled: True
#        publish_voxel_map: True
#        origin_z: 0.0
#        z_resolution: 0.1
#        z_voxels: 16
#        max_obstacle_height: 2.0
#        mark_threshold: 0
#        observation_sources: pointcloud
#        pointcloud:
#          topic: /merged_cloud
#          max_obstacle_height: 2.0
#          clearing: True
#          marking: True
#          data_type: "PointCloud2"
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        inflation_radius: 0.3
        cost_scaling_factor: 13.7
      always_send_full_costmap: True
  global_costmap_client:
    ros__parameters:
      use_sim_time: False
  global_costmap_rclcpp_node:
    ros__parameters:
      use_sim_time: False

map_server:
  ros__parameters:
    use_sim_time: False
    yaml_filename: "map.yaml"

map_saver:
  ros__parameters:
    use_sim_time: False
    save_map_timeout: 10000
    free_thresh_default: 0.25
    occupied_thresh_default: 0.65

planner_server:
  ros__parameters:
    expected_planner_frequency: 20.0
    use_sim_time: False
    planner_plugins: ["GridBased"]
    GridBased:
      # plugin: "smac_planner/SmacPlanner2D"
      # tolerance: 0.2                        # tolerance for planning if unable to reach exact pose, in meters
      # downsample_costmap: true              # whether or not to downsample the map
      # downsampling_factor: 2                # multiplier for the resolution of the costmap layer (e.g. 2 on a 5cm costmap would be 10cm)
      # allow_unknown: true                   # allow traveling in unknown space
      # max_iterations: 1000000               # maximum total iterations to search for before failing (in case unreachable), set to -1 to disable
      # max_on_approach_iterations: 1000      # maximum number of iterations to attempt to reach goal once in tolerance
      # max_planning_time: 2.0                # max time in s for planner to plan, smooth
      # cost_travel_multiplier: 2.0           # Cost multiplier to apply to search to steer away from high cost areas. Larger values will place in the center of aisles more exactly (if non-`FREE` cost potential field exists) but take slightly longer to compute. To optimize for speed, a value of 1.0 is reasonable. A reasonable tradeoff value is 2.0. A value of 0.0 effective disables steering away from obstacles and acts like a naive binary search A*.
      # use_final_approach_orientation: false # Whether to set the final path pose at the goal's orientation to the requested orientation (false) or in line with the approach angle so the robot doesn't rotate to heading (true)
      # smoother:
      #   max_iterations: 1000
      #   w_smooth: 0.5
      #   w_data: 0.2
      #   tolerance: 1e-10
      plugin: "nav2_navfn_planner/NavfnPlanner"
      tolerance: 0.02
      use_astar: true
      allow_unknown: true
      use_final_approach_orientation: false

planner_server_rclcpp_node:
  ros__parameters:
    use_sim_time: False

behavior_server:
  ros__parameters:
    costmap_topic: local_costmap/costmap_raw
    footprint_topic: local_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["backup", "wait"]
    backup:
      plugin: "nav2_behaviors/BackUp"
    wait:
      plugin: "nav2_behaviors/Wait"
    global_frame: map
    local_frame: odom
    robot_base_frame: base_link
    transform_timeout: 0.2
    use_sim_time: False
    simulate_ahead_time: 2.0
    max_rotational_vel: 0.3
    min_rotational_vel: -0.2
    rotational_acc_lim: 0.3

robot_state_publisher:
  ros__parameters:
    use_sim_time: False
